# Generated by Django 4.2.2 on 2023-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Пиччя')),
                ('description', models.TextField(verbose_name='Оисaние')),
                ('rating', models.FloatField(default=0, verbose_name='PейTинг')),
                ('url', models.URLField(verbose_name='Интернет-адрес')),
            ],
        ),
    ]
