# Generated by Django 4.2.2 on 2023-06-11 18:15

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_pizza_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ИMя')),
                ('phone', models.CharField(max_length=30, verbose_name='Тeле☀он')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ãa¹a')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='firstapp.pizza', verbose_name='Пиччa')),
            ],
        ),
    ]
